// Copyright 2022 Espressif Systems (Shanghai) PTE LTD
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef LV_CONF_H
#define LV_CONF_H

#ifdef __cplusplus
extern "C" {
#endif

#define CONFIG_LV_CONF_SKIP 1
#define CONFIG_LV_COLOR_DEPTH_16 1
#define CONFIG_LV_COLOR_DEPTH 16
#define CONFIG_LV_COLOR_MIX_ROUND_OFS 128
#define CONFIG_LV_COLOR_CHROMA_KEY_HEX 0x00FF00
#define CONFIG_LV_MEM_CUSTOM 1
#define CONFIG_LV_MEM_CUSTOM_INCLUDE "stdlib.h"
#define CONFIG_LV_MEM_BUF_MAX_NUM 16
#define CONFIG_LV_MEMCPY_MEMSET_STD 1
#define CONFIG_LV_DISP_DEF_REFR_PERIOD 30
#define CONFIG_LV_INDEV_DEF_READ_PERIOD 30
#define CONFIG_LV_DPI_DEF 130
#define CONFIG_LV_DRAW_COMPLEX 1
#define CONFIG_LV_SHADOW_CACHE_SIZE 0
#define CONFIG_LV_CIRCLE_CACHE_SIZE 10
#define CONFIG_LV_IMG_CACHE_DEF_SIZE 5
#define CONFIG_LV_DISP_ROT_MAX_BUF 10240
#define CONFIG_LV_USE_ASSERT_NULL 1
#define CONFIG_LV_USE_ASSERT_MALLOC 1
#define CONFIG_LV_ASSERT_HANDLER_INCLUDE "assert.h"
#define CONFIG_LV_USE_USER_DATA 1
#define CONFIG_LV_ATTRIBUTE_MEM_ALIGN_SIZE 1
#define CONFIG_LV_FONT_MONTSERRAT_8 1
#define CONFIG_LV_FONT_MONTSERRAT_10 1
#define CONFIG_LV_FONT_MONTSERRAT_12 1
#define CONFIG_LV_FONT_MONTSERRAT_14 1
#define CONFIG_LV_FONT_MONTSERRAT_16 1
#define CONFIG_LV_FONT_MONTSERRAT_18 1
#define CONFIG_LV_FONT_MONTSERRAT_20 1
#define CONFIG_LV_FONT_MONTSERRAT_22 1
#define CONFIG_LV_FONT_MONTSERRAT_24 1
#define CONFIG_LV_FONT_MONTSERRAT_26 1
#define CONFIG_LV_FONT_MONTSERRAT_28 1
#define CONFIG_LV_FONT_MONTSERRAT_30 1
#define CONFIG_LV_FONT_MONTSERRAT_32 1
#define CONFIG_LV_FONT_MONTSERRAT_34 1
#define CONFIG_LV_FONT_MONTSERRAT_36 1
#define CONFIG_LV_FONT_MONTSERRAT_38 1
#define CONFIG_LV_FONT_MONTSERRAT_40 1
#define CONFIG_LV_FONT_MONTSERRAT_42 1
#define CONFIG_LV_FONT_MONTSERRAT_44 1
#define CONFIG_LV_FONT_MONTSERRAT_46 1
#define CONFIG_LV_FONT_MONTSERRAT_48 1
#define CONFIG_LV_FONT_DEFAULT_MONTSERRAT_14 1
#define CONFIG_LV_TXT_ENC_UTF8 1
#define CONFIG_LV_TXT_BREAK_CHARS " ,.;:-_"
#define CONFIG_LV_TXT_LINE_BREAK_LONG_LEN 0
#define CONFIG_LV_TXT_COLOR_CMD "#"
#define CONFIG_LV_USE_ARC 1
#define CONFIG_LV_USE_BAR 1
#define CONFIG_LV_USE_BTN 1
#define CONFIG_LV_USE_BTNMATRIX 1
#define CONFIG_LV_USE_CANVAS 1
#define CONFIG_LV_USE_CHECKBOX 1
#define CONFIG_LV_USE_DROPDOWN 1
#define CONFIG_LV_USE_IMG 1
#define CONFIG_LV_USE_LABEL 1
#define CONFIG_LV_LABEL_TEXT_SELECTION 1
#define CONFIG_LV_LABEL_LONG_TXT_HINT 1
#define CONFIG_LV_USE_LINE 1
#define CONFIG_LV_USE_ROLLER 1
#define CONFIG_LV_ROLLER_INF_PAGES 7
#define CONFIG_LV_USE_SLIDER 1
#define CONFIG_LV_USE_SWITCH 1
#define CONFIG_LV_USE_TEXTAREA 1
#define CONFIG_LV_TEXTAREA_DEF_PWD_SHOW_TIME 1500
#define CONFIG_LV_USE_TABLE 1
#define CONFIG_LV_USE_ANIMIMG 1
#define CONFIG_LV_USE_CALENDAR 1
#define CONFIG_LV_USE_CALENDAR_HEADER_ARROW 1
#define CONFIG_LV_USE_CALENDAR_HEADER_DROPDOWN 1
#define CONFIG_LV_USE_CHART 1
#define CONFIG_LV_USE_COLORWHEEL 1
#define CONFIG_LV_USE_IMGBTN 1
#define CONFIG_LV_USE_KEYBOARD 1
#define CONFIG_LV_USE_LED 1
#define CONFIG_LV_USE_LIST 1
#define CONFIG_LV_USE_METER 1
#define CONFIG_LV_USE_MSGBOX 1
#define CONFIG_LV_USE_SPINBOX 1
#define CONFIG_LV_USE_SPINNER 1
#define CONFIG_LV_USE_TABVIEW 1
#define CONFIG_LV_USE_TILEVIEW 1
#define CONFIG_LV_USE_WIN 1
#define CONFIG_LV_USE_SPAN 1
#define CONFIG_LV_SPAN_SNIPPET_STACK_SIZE 64
#define CONFIG_LV_USE_THEME_DEFAULT 1
#define CONFIG_LV_THEME_DEFAULT_GROW 1
#define CONFIG_LV_THEME_DEFAULT_TRANSITION_TIME 80
#define CONFIG_LV_USE_THEME_BASIC 1
#define CONFIG_LV_USE_FLEX 1
#define CONFIG_LV_USE_GRID 1
#define CONFIG_LV_USE_FS_STDIO 0
#define CONFIG_LV_USE_FS_POSIX 0
#define CONFIG_LV_USE_FS_WIN32 0
#define CONFIG_LV_USE_FS_FATFS 0
#define CONFIG_LV_USE_SNAPSHOT 1
#define CONFIG_LV_BUILD_EXAMPLES 1
#define CONFIG_LV_SPRINTF_CUSTOM 1
#define CONFIG_LV_FONT_FMT_TXT_LARGE 1
#define CONFIG_LV_USE_QRCODE 1
#define CONFIG_LV_USE_PERF_MONITOR 1
#define CONFIG_LV_COLOR_SCREEN_TRANSP 1
#define CONFIG_LV_USE_FONT_COMPRESSED 1
#define CONFIG_LV_MEM_SIZE_KILOBYTES 48
#define CONFIG_LV_EXTERNAL_DATA_AND_DESTUCTOR 1

#ifdef __cplusplus
}
#endif

#endif /*LV_CONF_H*/